### ISSUE TITLE
vim cannot find YCM core lib

### ISSUE THREAD

**Issue by slxiao** [feiyuw/vim.d#1]
Using
> cd ~/.vim/bundle/YouCompleteMe
./install.py

The vim cannot find YCM core lib, and YCM is not effective.

After several trys, I found using
> cd ~/.vim/**plugged**/YouCompleteMe
./install.py

It succeeds.

I don't know why I have two same directories "bundle" and "plugged" under ~/.vim. And configuration in .vimrc is using plugged, not bundle.

**Comment by feiyuw** [comment]
bundle should be deleted, vim plugin manager has been switched to plug

**Comment by feiyuw** [comment]
README updated!
